# Generated by Django 5.1.1 on 2024-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("tagline", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("location", models.CharField(max_length=50)),
                ("average_price", models.IntegerField()),
                ("average_rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("age", models.IntegerField()),
                ("liked_places", models.JSONField()),
                ("visited_places", models.JSONField()),
            ],
        ),
    ]
