# Generated by Django 5.1.1 on 2024-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="liked_places",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="visited_places",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
